## 第一课 神经网络和深度学习

### 2.11 向量化

In [1]:
import numpy as np

a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [2]:
import time # 导入时间库
a = np.random.rand(1000000) # 通过round随机得到两个一百万维度的数组
b = np.random.rand(1000000)

# 向量化的版本
tic = time.time()
c = np.dot(a,b)
toc = time.time()

print(c)
print("Vectorized version:" + str(1000*(toc-tic)) + "ms")

# 非向量化版本
c = 0
tic = time.time()
for i in range(1000000):
    c += a[i] * b[i]
toc = time.time()

print(c)
print("For loop:" + str(1000*(toc-tic)) + "ms")

250377.8658626253
Vectorized version:5.983114242553711ms
250377.86586262478
For loop:574.3145942687988ms


### 2.15 Python 中的广播

In [1]:
import numpy as np

A = np.array([[56.0,0.0,4.4,68.0],
             [1.2,104.0,52.0,8.0],
             [1.8,135.0,99.0,0.9]])
print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [2]:
cal = A.sum(axis=0)
print(cal)

[ 59.  239.  155.4  76.9]


In [3]:
percentage = 100 * A / cal.reshape(1,4)
print(percentage)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


### 2.16 关于python_numpy向量的说明

In [4]:
import numpy as np

a = np.random.randn(5)

In [5]:
print(a)

[-0.73869351  0.58046698  0.9875773  -0.7653828  -0.37838839]


In [6]:
# 这是一个一维数组，它既不是行向量也不是一个列向量
# 不要使用这种数组的结构：(n,)
print(a.shape)

(5,)


In [7]:
print(a.T)

[-0.73869351  0.58046698  0.9875773  -0.7653828  -0.37838839]


In [8]:
print(np.dot(a, a.T))

2.586907532881364


**要使用矩阵类型**:

In [9]:
a = np.random.randn(5,1) # 列向量
print(a)

[[-0.33563023]
 [-0.46876746]
 [ 0.07963945]
 [ 0.0264668 ]
 [ 1.34669447]]


In [10]:
print(a.T)

[[-0.33563023 -0.46876746  0.07963945  0.0264668   1.34669447]]


In [11]:
print(np.dot(a, a.T))

[[ 1.12647650e-01  1.57332529e-01 -2.67294062e-02 -8.88305897e-03
  -4.51991372e-01]
 [ 1.57332529e-01  2.19742931e-01 -3.73323818e-02 -1.24067758e-02
  -6.31286544e-01]
 [-2.67294062e-02 -3.73323818e-02  6.34244170e-03  2.10780155e-03
   1.07250004e-01]
 [-8.88305897e-03 -1.24067758e-02  2.10780155e-03  7.00491636e-04
   3.56426966e-02]
 [-4.51991372e-01 -6.31286544e-01  1.07250004e-01  3.56426966e-02
   1.81358599e+00]]


In [12]:
assert(a.shape == (5,1))