### h5py简单介绍
参考自: [python库——h5py入门讲解](https://blog.csdn.net/ban_xicheng/article/details/80430767)

h5py文件是存放两类对象的容器，数据集(dataset)和组(group)，dataset类似数组类的数据集合，和numpy的数组差不多。group是像文件夹一样的容器，它好比python中的字典，有键(key)和值(value)。group中可以存放dataset或者其他的group。”键”就是组成员的名称，”值”就是组成员对象本身(组或者数据集)，下面来看下如何创建组和数据集。

#### 1. 创建一个h5py文件

In [1]:
import h5py
# 要是读取文件的话，就把w换成r
f = h5py.File("myh5py.hdf5","w")

#### 2. 创建dataset数据集

In [2]:
# dset1是数据集的name，(20,)代表数据集的shape，i代表的是数据集的元素类型
d1 = f.create_dataset("dset1",(20,),'i')
for key in f.keys():
    print(key)
    print(f[key].name)
    print(f[key].shape)
    print(f[key][:])

dset1
/dset1
(20,)
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


**赋值**

In [3]:
import h5py
import numpy as np

# f=h5py.File("myh5py.hdf5", "w")
# d1=f.create_dataset("dset1", (20,), 'i')
# 赋值
d1[...]=np.arange(20)
#或者可以直接按照下面的方式创建数据集并赋值
f['dset2']=np.arange(15)

for key in f.keys():
    print(f[key].name)
    print(f[key][:])

/dset1
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
/dset2
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


如果有现成的numpy数组，那么可以在创建数据集的时候就赋值，这个时候就不必指定数据的类型和形状了，只需要把数组名传给参数data。

In [4]:
a = np.arange(7)
d2 = f.create_dataset("dset3",data=a)
for key in f.keys():
    print(f[key].name)
    print(f[key][:])

/dset1
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
/dset2
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
/dset3
[0 1 2 3 4 5 6]


---
**三种创建方式混合_代码如下**

In [5]:
import h5py
import numpy as np
f = h5py.File("myh5py2.hdf5","w")
# 分别用三种创建数据集方式创建dset1,dset2,dset3这三个数据集
a = np.arange(5)
d1 = f.create_dataset("dset1",data=a)

d2 = f.create_dataset("dset2",(3,4),'i')
d2[...] = np.arange(12).reshape((3,4))

f["dset3"] = np.arange(15)

for key in f.keys():
    print(f[key].name)
    print(f[key][:])

/dset1
[0 1 2 3 4]
/dset2
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
/dset3
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


#### 3. 创建group组

In [6]:
import h5py
import numpy as np
f=h5py.File("myh5py.hdf5","a")
 
#创建一个名字为bar的组
g1=f.create_group("bar")
 
#在bar这个组里面分别创建name为dset1,dset2的数据集并赋值。
g1["dset1"]=np.arange(10)
g1["dset2"]=np.arange(12).reshape((3,4))
 
for key in g1.keys():
    print(g1[key].name)
    print(g1[key][:])

/bar/dset1
[0 1 2 3 4 5 6 7 8 9]
/bar/dset2
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [1]:
# 示例2
import h5py
import numpy as np
f = h5py.File("myh5py3.hdf5","w")

# 创建组bar1,组bar2，数据集dset
g1 = f.create_group("bar1")
g2 = f.create_group("bar2")
d = f.create_dataset("dset",data=np.arange(10))

# 在bar1组里面创建一个组car1和一个数据集dset1
c1 = g1.create_group("car1")
d1 = g1.create_dataset("dset1",data=np.arange(10))

# 在bar2组里面创建一个组car2和一个数据集dset2
c2 = g2.create_group("car2")
d2 = g2.create_dataset("dset2",data=np.arange(10))

# 根目录下的组和数据集
print(".............")
for key in f.keys():
    print(f[key].name)

# bar1这个组下面的组和数据集
print(".............")
for key in g1.keys():
    print(g1[key].name)
 
 
# bar2这个组下面的组和数据集
print(".............")
for key in g2.keys():
    print(g2[key].name)
    
# car1组和car2组
print(".............")
print(c1.keys())
print(c2.keys())

.............
/bar1
/bar2
/dset
.............
/bar1/car1
/bar1/dset1
.............
/bar2/car2
/bar2/dset2
.............
<KeysViewHDF5 []>
<KeysViewHDF5 []>
